---
name: ðŸ§Ÿ Encoded Dump


on:
  workflow_dispatch:


jobs:
  encoded_dump:
    runs-on: ubuntu-latest
    steps:
      - name: "ðŸ§Ÿ Extract Workflow 001 Secret"
        env:
          WORKFLOW_SECRET: ${{ secrets.WORKFLOW_001 }}
        run: |
          echo "WORKFLOW_SECRET (***)    = ${WORKFLOW_SECRET}"

          echo "WORKFLOW_SECRET (base64) = $(echo ${WORKFLOW_SECRET} | base64)"

          echo "Copy the above value, and then execute locally:"

          echo "echo PASTE_HERE | base64 -D"

